---

- name: set fact for docker-seed-local
  when: 
    - lookup('ansible.builtin.env', 'SEED_NAME') != ''
    - ansible_connection == 'local'
  ansible.builtin.set_fact:
    seed_in_docker_connect_local: true

- name: set dir_remote_path:docker-seed-local
  when: seed_in_docker_connect_local is defined
  ansible.builtin.set_fact:
    dir_remote_path: "/workspace/{{ dir_path }}"

- name: set dir_remote_path
  when: seed_in_docker_connect_local is undefined
  ansible.builtin.set_fact:
    dir_remote_path: "{{ workspace.path }}/{{ dir_path }}"

- name: copy dir to remote
  when: seed_in_docker_connect_local is undefined
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/"
    dest: "{{ dir_remote_path }}"
    owner: root
    group: root
    mode: '0777'