all:
  hosts:
    ub.lan:
  children:
    docker-manager:
      hosts:
        ub.lan:
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3
      vars:
        workspace:
          path: "/workspace"