name: docker-seed-cli

on:
  workflow_dispatch:
  create:
    tags:
      - "*"
  push:
    tags:
      - "*"
    branches:
      - "*"
    paths:
      - 'cli/**'

jobs:
  gallery:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - 
        name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}